spring:
  main:
    banner_mode: 'off'

server:
  port: 8888

zuul:
  routes:
    sample:
      path: /sample/**
      url: http://localhost:8080/app
    logout:
      path: /logout
      url: http://nowhere


